# Generated by Django 4.0.2 on 2022-04-07 23:01

import auth_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=264)),
                ('is_staff', models.BooleanField(default=False, help_text='Determines Whether They Can Log in this Site or not', verbose_name='staff_status')),
                ('is_active', models.BooleanField(default=True, help_text='Determines Whether their Account Status is Active or not', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'User',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=264)),
                ('last_name', models.CharField(blank=True, max_length=264)),
                ('profile_pic', models.ImageField(blank=True, default='/profile/default.jpg', upload_to=auth_api.models.upload_image)),
                ('cover_pic', models.ImageField(blank=True, default='/profile/defaultCover.png', upload_to=auth_api.models.upload_cover)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
                'db_table': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile_view', to='auth_api.userprofile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile_viewer', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Profile Views',
                'db_table': 'User Profile Views',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_of_me', to='auth_api.userprofile')),
                ('myfollowers', models.ManyToManyField(blank=True, related_name='my_followers', to='auth_api.UserProfile')),
            ],
            options={
                'verbose_name_plural': "User Follower's",
                'db_table': "User Follower's",
            },
        ),
    ]
