# Generated by Django 4.0.2 on 2022-04-07 23:02

import Profile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Skill List',
                'db_table': 'Skill List',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Fulltime', 'Full-Time'), ('Parttime', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Selfemployed', 'Self-employed'), ('Freelance', 'Freelance')], max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Work Experience',
                'db_table': 'User Work Experience',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_skill', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillList', to='Profile.skilllist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myskills', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Skills',
                'db_table': 'User Skills',
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myheader', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Headline',
                'db_table': 'User Headline',
            },
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Profile.models.upload_featured)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myfeatured', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Featured',
                'db_table': 'User Featured',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myeducation', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Education',
                'db_table': 'User Education',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contactme', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Contact Info',
                'db_table': 'User Contact Info',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myabout', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User About',
                'db_table': 'User About',
            },
        ),
    ]
