# Generated by Django 4.0.2 on 2022-04-07 23:02

import Job.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Job.models.photo_path)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=Job.models.cover_path)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_company', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Company',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='CompanyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('isOpen', models.BooleanField(default=True)),
                ('applied', models.ManyToManyField(blank=True, related_name='company_job_appliers', to='auth_api.UserProfile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job_post', to='Job.company')),
            ],
            options={
                'verbose_name_plural': 'CompanyJobs',
                'db_table': 'CompanyJobs',
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='CompanyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Job.models.post_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycompanypost', to='Job.company')),
            ],
            options={
                'verbose_name_plural': 'Company Post',
                'db_table': 'Company Post',
                'ordering': ('-upload_date',),
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_company_jobs', to='Job.companyjobs')),
                ('me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_job_savedby_Me', to='auth_api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'My Saved Jobs',
                'db_table': 'My Saved Jobs',
            },
        ),
        migrations.CreateModel(
            name='CompanyPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=264)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post_commenter', to='auth_api.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post_comment_post', to='Job.companypost')),
            ],
            options={
                'verbose_name_plural': 'CompanyPost Comment',
                'db_table': 'CompanyPost Comment',
            },
        ),
        migrations.CreateModel(
            name='CompanyFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_of_myCompanny', to='Job.company')),
                ('myfollowers', models.ManyToManyField(blank=True, related_name='my_company_followers', to='auth_api.UserProfile')),
            ],
            options={
                'verbose_name_plural': "Company Follower's",
                'db_table': "Company Follower's",
            },
        ),
        migrations.CreateModel(
            name='CompanyAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('10', '1-10'), ('50', '10-50'), ('100', '50-100'), ('500', '100-500'), ('1000', '500-1000'), ('5000', '1000-5000'), ('10000', '5000-10000'), ('10000', '10000+')], default=None, max_length=50, null=True)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Government', 'Government'), ('Private', 'Private'), ('Nonprofit', 'Nonprofit')], default=None, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('founded', models.DateField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mycompanyabout', to='Job.company')),
            ],
            options={
                'verbose_name_plural': 'Company About',
                'db_table': 'Company About',
            },
        ),
        migrations.CreateModel(
            name='CompanyPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('liked', models.BooleanField(default=False)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post_liker', to='auth_api.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post_post_like', to='Job.companypost')),
            ],
            options={
                'verbose_name_plural': 'CompanyPost Like',
                'db_table': 'CompanyPost Like',
                'unique_together': {('post', 'liker')},
            },
        ),
    ]
