# Generated by Django 4.0.2 on 2022-04-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjobs',
            unique_together={('job', 'me')},
        ),
    ]
